"""
python/sim_helpers.py — plotting utilities for trial simulation results.

Used by Project 05 (trial simulation) to visualise power curves and
operating characteristics tables generated by the R scripts.
"""

from __future__ import annotations

import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker

matplotlib.use("Agg")

plt.rcParams.update(
    {
        "figure.facecolor": "white",
        "axes.facecolor": "white",
        "axes.grid": True,
        "grid.color": "0.88",
        "grid.linewidth": 0.8,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "font.size": 11,
        "axes.titlesize": 12,
        "axes.labelsize": 11,
    }
)


def plot_power_curve(
    results_df: pd.DataFrame,
    n_col: str = "n_per_arm",
    power_col: str = "power",
    dose_col: str = "dose",
    ci_lower_col: str | None = "power_ci_lower",
    ci_upper_col: str | None = "power_ci_upper",
    target_power: float = 0.80,
    save_path: str | None = None,
) -> plt.Figure:
    """
    Plot power vs sample size per arm, one curve per dose.

    Parameters
    ----------
    results_df    : DataFrame with columns for n, power, dose, and optionally CI.
    n_col         : Column name for sample size per arm.
    power_col     : Column name for power estimate.
    dose_col      : Column name for dose label.
    ci_lower_col  : Column for lower CI bound (plotted as shaded band).
    ci_upper_col  : Column for upper CI bound.
    target_power  : Reference line for target power (default 0.80).
    save_path     : Base path to save PNG + SVG.

    Returns
    -------
    matplotlib Figure.
    """
    fig, ax = plt.subplots(figsize=(9, 5))

    doses   = sorted(results_df[dose_col].unique())
    colours = plt.cm.viridis(np.linspace(0.15, 0.85, len(doses)))

    for dose, colour in zip(doses, colours):
        sub = results_df[results_df[dose_col] == dose].sort_values(n_col)
        ax.plot(sub[n_col], sub[power_col], marker="o", label=f"{dose} mg",
                colour=colour, linewidth=2, markersize=5)
        if ci_lower_col and ci_upper_col and ci_lower_col in sub.columns:
            ax.fill_between(
                sub[n_col],
                sub[ci_lower_col],
                sub[ci_upper_col],
                colour=colour,
                alpha=0.15,
            )

    ax.axhline(target_power, linestyle="--", colour="tomato", linewidth=1.5,
               label=f"{int(target_power*100)}% target")
    ax.set_xlabel("Sample size per arm (n)")
    ax.set_ylabel("Power")
    ax.set_ylim(0, 1.05)
    ax.yaxis.set_major_formatter(ticker.PercentFormatter(xmax=1))
    ax.set_title("Power Curve — EC₅₀ Estimation Precision")
    ax.legend(title="Dose", bbox_to_anchor=(1.01, 1), loc="upper left")
    plt.tight_layout()

    if save_path is not None:
        png = save_path if save_path.endswith(".png") else save_path + ".png"
        plt.savefig(png, dpi=300, bbox_inches="tight")
        plt.savefig(png.replace(".png", ".svg"), bbox_inches="tight")

    return fig


def summarize_trial_results(results_df: pd.DataFrame) -> pd.DataFrame:
    """
    Pivot trial simulation results into an operating characteristics table.

    Returns a DataFrame suitable for gt or pandas styling with columns:
    n_per_arm, dose, power, type_i_error, ec50_bias, ec50_rmse, coverage.
    """
    required = ["n_per_arm", "dose"]
    missing  = [c for c in required if c not in results_df.columns]
    if missing:
        raise ValueError(f"summarize_trial_results: missing columns {missing}")
    return results_df.sort_values(["dose", "n_per_arm"]).reset_index(drop=True)
